framework:
    messenger:
        transports:
            product_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    queues:
                        product_queue: ~
        routing:
            Shared\Bundle\Messaging\ProductMessage: product_transport
