networks:
  app_network:
    external: true

services:
  product_service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: product_service
    depends_on:
      - product_db
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@product_db:5432/product_db?serverVersion=15&charset=utf8"
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./extend-php.ini:/usr/local/etc/php/conf.d/extend-php.ini
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - app_network

  product_db:
    image: postgres:15
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db_data:
